### ISSUE TITLE
Albums with special characters

### ISSUE THREAD

**Issue by starcrash-13** [pranjalagg/spdl#10]
Cannot download a playlist whose name includes, or whose tracks albums include, a "?". I have tried removing the character from the Playlist title, adding it to a different playlist, adding a custom outpath, etc. There is nothing I can do to force these files to download.

**Comment by pranjalagg** [comment]
Thank you so much for raising this @starcrash-13.
This should now be resolved in PR #12

**Comment by starcrash-13** [comment]
Thank you! Also do you have any information about what causes the 'link' error? This doesn't seem to be on your end, it happens with the same tracks on the spotifydown website. It happens with random tracks, sometimes they'll work the next day, or a week later, sometimes they'll never download.
