### ISSUE TITLE
Some songs give 500 error but work on the website

### ISSUE THREAD

**Issue by exadeci** [pranjalagg/spdl#11]
~~I've been using this great too with no issues but it seems that in the past few weeks every new song in my `sync` file won't download and will give me the error `link` I tried debugging the code but all I've found is that the server returns a 500 for some songs.~~

~~This one for example gives a 500:
`https://open.spotify.com/track/5L67BQarXLbH83apGELFPk`~~

Nevermind it does fail on the website too it pretends it worked but then gives a 70kb mp3

PS: also mutagen is missing from `requirements.txt`

**Comment by pranjalagg** [comment]
Thanks for raising this. The requirements file is now updated.

Regarding the songs, I have noticed that too recently and was thinking of using a fallback method in case there is an error repeatedly for a song, but have been a bit busy lately. Would work on something someday, maybe.
