### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\uccab' in position 24: character maps to <undefined>

### ISSUE THREAD

**Issue by dialeleven** [pranjalagg/spdl#14]
Getting an error when dealing with non-English characters in the title.

python main.py -link https://open.spotify.com/track/6qNmSfA3puyB5n5PRbE6RC?si=e338ad1bf9d94737

**Comment by pranjalagg** [comment]
Hi @dialeleven,
It works on my end, can you try it again?
Also, what platform are you using the tool in?

**Comment by dialeleven** [comment]
Weird, it works now without the error message. I'm running Python 3.12.4 on Windows 11 Home.
