### ISSUE TITLE
Suggestion : Manage multilingual link

### ISSUE THREAD

**Issue by lucasroyerdev** [pranjalagg/spdl#17]
Hi, 

First, thank you for your great work with work fast and perfectly.

I just have a little suggestion to improve the software : i'm french and when I copy a track link straight from Spotify interface, the link has this format : https://open.spotify.com/intl-fr/track/XXXXXXXXXX. "intl-fr" is added.

The software doesn't manage it and I have to transform URL to https://open.spotify.com/track/XXXXXXXXXX.

I think it can be quickly modified in the code to manage all different country codes.

Thank you again

EDIT : Solution implemented here : https://github.com/aliocha44/spdl/tree/playlist-download

I changed 
```
def check_track_playlist(link, outpath, create_folder, trackname_convention):
    resolve_path(outpath)
    # if "/track/" in link:
    if re.search(r".*spotify\.com\/track\/", link):
        # return "track"
        download_track(link, outpath, trackname_convention) 
```
To
```
def check_track_playlist(link, outpath, create_folder, trackname_convention):
    resolve_path(outpath)
    # if "/track/" in link:
    if re.search(r".*spotify\.com\/(?:intl-[a-zA-Z]{2}\/)?track\/", link):
        # return "track"
        download_track(link, outpath, trackname_convention)
```

**Comment by pranjalagg** [comment]
Hi @aliocha44 
Thank you so much for bringing this up. I have added the suggested changes to the main branch.

I saw your engagement on other issues as well, thank you so much for showing interest in the project. I would really appreciate it if you could raise PRs for those issues for the benefit of the entire community.

Thanks!

**Comment by lucasroyerdev** [comment]
Hi ! 

Thank you for your message ! I will raise a PR with pleasure for this feature. For playlist download, I'm afraid I changed a bit too much the initial code so I prefer to continue on the branch to finish the work in progress before change everything !

Thank you

**Comment by pranjalagg** [comment]
No worries. This was a straightforward addition, so it is taken care of. For other things, I understand entirely; feel free to raise a PR anytime.
