### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by DragonHeart69** [pranjalagg/spdl#2]
An option to choose the file name would be helpful.
Now they are saved as <title> - <artist>.
I prefer it in the reverse order: <artist> - <title>.

Grtz Dimitri

**Comment by pranjalagg** [comment]
Hi @DragonHeart69,
Thank you for the suggestion. I have implemented this. Now everytime you download a track or playlist, you would be pormpted to select the naming convention you want to use for the tracks.

For the sync feature as well, whenever a new sync file is created, the user is prompted to select the naming convention and the information is stored in the sync file so the user does not have to provide the same information again.

Feel free to reopen the issue, if you encounter a problem.
