### ISSUE TITLE
Download stuck (Infinite downloading)

### ISSUE THREAD

**Issue by Aether0Pneuma** [pranjalagg/spdl#22]
After playlist identified, downloading begins, but it stucks on 1'st track and nothing happens.
![изображение_2024-10-19_230642096](https://github.com/user-attachments/assets/739425e5-5d7d-4241-9583-a32a34f21b0c)

**Comment by pranjalagg** [comment]
Hi @FuriFull ,
I cannot reproduce the issue at my end. Would you mind mentioning the link that you are using and the log file contents (spdl.log)

**Comment by Aether0Pneuma** [comment]
> Hi @FuriFull , I cannot reproduce the issue at my end. Would you mind mentioning the link that you are using and the log file contents (spdl.log)

Fixed by running CMD with admin rights, otherwise no results

**Comment by pranjalagg** [comment]
It might be due to insufficient write permissions to the folder you are trying to save the tracks to. But glad that the issue was resolved.
