### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by bejas** [pranjalagg/spdl#5]
Album name and release date are missing.

**Comment by pranjalagg** [comment]
Could you please elaborate on this? Are the album name and release date missing from all the tracks, or are they missing only for some specific tracks?

**Comment by starcrash-13** [comment]
I do not have issues with the album name or release date, but track numbers are always missing, and the album art is often a 300x300, as opposed to the 640x640 provided on Spotify.

**Comment by pranjalagg** [comment]
Hi @starcrash-13,
The feature to include the track number in the metadata is now added. As for the cover art, I think now for most of the cases it is 640x640.
