### ISSUE TITLE
Not Seeing Album Art

### ISSUE THREAD

**Issue by tonberry-sensei** [pranjalagg/spdl#7]
First, this is amazing brother. Thank you!

When I'm downloading a playlist, the thumbnail cover art doesn't show for any of the songs. I am using Windows 10.

**Comment by tonberry-sensei** [comment]
Update: I see the album art on my phone, but not on my computer (Windows 10). Just an observation.

**Comment by pranjalagg** [comment]
If the cover art is visible on your phone, it means that the metadata for the cover art is present with the track. It might be some setting in your PC that is preventing them to display correctly.
