### ISSUE TITLE
Solved: Attach_cover_art not working

### ISSUE THREAD

**Issue by Fabiuas** [pranjalagg/spdl#8]
Heya, 

Love your project and your code, very well structured!

For me the covert art was not showing up, but I have written some code myself that fixes this problem. Would you be interested in this?

Kind regards

**Comment by pranjalagg** [comment]
Hi @Fabiuas,
Glad you found it useful. Regarding the cover art, could you please clarify what the exact issue was?
Also, feel free to create a pull request with your changes, I would be happy to merge them.

**Comment by Fabiuas** [comment]
Hi, not really sure what the exact issue was, but the mp3 files didnt have a covert art after downloading them using you code. In another project of mine, I managed to attach my pictures to mp3 files, so i just implemented that code into yours. 

I am not that knowledgable with GitHub, so i'm not sure what a pull request etc. is. Instead I'll just drop the function here. Only the **attach_cover_art** function changed and i put **.content** at the end of your cover_art variable as this method required the actual jpeg as input.

```
import os
import re
import logging
from mutagen.mp3 import MP3
from mutagen.id3 import ID3, APIC, error

cover_art = requests.get(resp['metadata'].cover).content

def attach_cover_art(trackname, cover_art, outpath):
    
    trackname = re.sub(TRACKNAME_REGEX, "_", trackname)
    filepath = os.path.join(outpath, f"{trackname}.mp3")

    try:
        audio = MP3(filepath, ID3=ID3)
    except error as e:
        logging.error(f"Error loading MP3 file from {filepath} --> {e}")
        print(f"\tError loading MP3 file --> {e}")
        return

    if audio.tags is None:
        try:
            audio.add_tags()
        except error as e:
            logging.error(f"Error adding ID3 tags to {filepath} --> {e}")
            print(f"\tError adding ID3 tags --> {e}")
            return 
        
    audio.tags.add(APIC(encoding=1,mime='image/jpeg',type=3,desc=u'Cover',data=cover_art))
    audio.save(filepath, v2_version=3, v1=2)
```

**Comment by pranjalagg** [comment]
Hi @Fabiuas,
Thank you so much for your contribution. These changes have now been merged into the main branch.
